language: python
python:
  - 3.7
cache: pypi
branches:
  only:
    - master
before_install:
  - sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_10.x" | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm install -g yarn
jobs:
  include:
    - stage: test
      script:
        - make install
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
        - make test
    - stage: deploy
      if: branch = master
      script:
        - git config --global user.name "${GH_NAME}"
        - git config --global user.email "${GH_EMAIL}"
        - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
        - cd docs && yarn && GIT_USER="${GH_NAME}" yarn deploy
