dist: xenial
language: python
python:
  - 3.6
  - 3.7
cache: pypi
branches:
  only:
    - master
jobs:
  include:
    name: Test
    script:
      - make install
      - make test
    name: Docs
    script:
      - git config --global user.name "${GH_NAME}"
      - git config --global user.email "${GH_EMAIL}"
      - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
      - cd docs && yarn && GIT_USER="${GH_NAME}" yarn deploy
