matrix:
  include:
    - language: python
      python: 3.7
      before_script:
        - make install
      script:
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
        - make test
    - language: node_js
      node_js: '10'
      cache:
        yarn: true
      if: branch = master
      script:
        - git config --global user.name "${GH_NAME}"
        - git config --global user.email "${GH_EMAIL}"
        - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
        - cd docs && yarn && GIT_USER="${GH_NAME}" yarn deploy