name: Pull Build

on:
  pull_request:
    branches:
    - master

jobs:
  Test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]
        python-version: [3.6, 3.7, 3.8]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: borales/actions-yarn@v2.0.0

      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python Dependancies
        run: make install

      - name: Run Python test suite
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          make test

      - name: Install documentation dependancies & build docs
        run: |
          cd docs
          yarn
          yarn build
